### ISSUE TITLE
Getting build errors when compiling for ios in xcode

### ISSUE THREAD

**Issue by rubiktubik** [EricLBuehler/mistral.rs#1127]
Hi, @EricLBuehler  first, thank you for the amazing library and your work.

I want to use mistral-rs on ios with flutter and https://cjycode.com/flutter_rust_bridge/ but getting the following build message:

```
Error (Xcode): instruction requires: fullfp16
Error (Xcode): could not compile `gemm-f16` (lib) due to 11 previous errors
```

I not sure if it is related to mistral-rs. But fp16 is mostly need for machine-learning i think.

I added mistral-rs like this to my cargo.toml:

```toml
mistralrs = { git = "https://github.com/EricLBuehler/mistral.rs.git", branch = "master", features = [
    "metal",
] }
```

I have also tried to use rust nightly with rustflags in the config.toml with (which is mentioned here https://github.com/sarah-quinones/gemm/issues/31)

```toml
[build]
rustflags = [
    "-Ctarget-feature=+fp16,+fhm"
]
```
But still getting the same error

**Comment by EricLBuehler** [comment]
Hi @rubiktubik, thanks for the issue!

It appears that this issue is related to the upstream `gemm` crate. Could you please provide the full error/compilation log in pastebin or an equivalent? I haven't run into this error, it seems the issue you linked `gemm` contains the error.

**Comment by rubiktubik** [comment]
I seems this error is also related to using a debug build with xcode. 
I will try to figure out more.

**Comment by rubiktubik** [comment]
I could reproduce this issue with:

`cargo build --target aarch64-apple-ios`

**Comment by rubiktubik** [comment]
Creating `.cargo/config.toml` 

with the following content seams fix the issue

```toml
[target.aarch64-apple-darwin]
[build]
rustflags = ["-C", "target-cpu=native"]
```

Using 

```toml
[build]
rustflags = [
    "-Ctarget-feature=+fp16,+fhm"
]
```

also works
