### ISSUE TITLE
Container image fails to start with 'Unable to dynamically load the "cuda" shared library'

### ISSUE THREAD

**Issue by sammcj** [EricLBuehler/mistral.rs#478]
**Describe the bug**

When the mistralrs container using the official Dockerfile.cuda-all starts it crashes with:

```
thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cudarc-0.11.6/src/lib.rs:98:5:
Unable to dynamically load the "cuda" shared library - searched for library names: ["cuda", "nvcuda"]. Ensure that `LD_LIBRARY_PATH` has the correct path to the installed library. If the shared library is present on the system under a different name than one of those listed above, please open a GitHub issue.
```

```
services:
  &name mistralrs:
    build:
      context: https://github.com/EricLBuehler/mistral.rs.git#master
      dockerfile: Dockerfile.cuda-all
      args:
        - FEATURES=cuda,flash-attn,cudnn
        - CUDA_COMPUTE_CAP=86
    container_name: *name
    hostname: *name
    ports:
      - 80
    volumes:
      - /mnt/llm/mistralrs/data:/data
      - /mnt/llm/models:/models
    command: gguf -m . -f /models/DeepSeek-Coder-V2-Instruct.IQ2_XXS.gguf
	devices:
	  - /dev/nvidia0:/dev/nvidia0
	  - /dev/nvidia1:/dev/nvidia1
	  - /dev/nvidia2:/dev/nvidia2
	runtime: nvidia
	deploy:
	  resources:
	    reservations:
	      devices:
	        - driver: nvidia
	          count: all
	          capabilities: ["compute", "utility", "graphics"]
	environment:
	  - NVIDIA_VISIBLE_DEVICES=all
	  - NVIDIA_DRIVER_CAPABILITIES=all
```

**Latest commit**

- 615a10e816aa10bc38b21c683993ebe7b73c187a (master as of 2024-06-25 9:32AM AEST)
