### ISSUE TITLE
Mixtral crashes with: `Error: invalid type: null, expected usize at line 23 column 24`

### ISSUE THREAD

**Issue by csicar** [EricLBuehler/mistral.rs#615]
## Describe the bug

Running plain mixtral, from mistralai using docker, mistral.rs errors out. To reproduce:
```yaml
# docker-compose.yml
services:
  mistralrs:
    image: ghcr.io/ericlbuehler/mistral.rs:cuda-86-sha-4ae9bc9
    command: plain -m mistralai/Mixtral-8x7B-Instruct-v0.1 -a mixtral
    environment:
      - MISTRALRS_DEBUG=1
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
```

```console
$ docker compose up -d; docker compose logs -f
...
mistralrs-1  | 2024-07-23T21:47:43.164514Z  INFO mistralrs_core::pipeline::normal: Loading model `mistralai/Mixtral-8x7B-Instruct-v0.1` on cuda[0].
mistralrs-1  | Error: invalid type: null, expected usize at line 23 column 24
mistralrs-1 exited with code 1
```

## Latest commit or version

I'm using `ghcr.io/ericlbuehler/mistral.rs:cuda-86-sha-4ae9bc9`

## Solution

IMHO, this is caused by the `sliding_window` field in [`config.json` from Mixtral](https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1/blob/main/config.json#L23) using the value `null`. Thus a change similar to https://github.com/EricLBuehler/mistral.rs/pull/83 should fix this.
